# Generated by Django 4.1.5 on 2023-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.SlugField(max_length=255)),
                ('des', models.CharField(max_length=255)),
                ('example', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
