# Generated by Django 4.1.5 on 2023-01-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
