# Generated by Django 4.1.5 on 2023-01-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
