# Generated by Django 4.1.5 on 2023-01-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
