# Generated by Django 4.1.5 on 2023-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
