# Generated by Django 4.1.5 on 2023-01-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='translate_word',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
